### ISSUE TITLE
404 Client Error: NOT FOUND during progress updates

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mydata#135]
The following error has been observed in MyData v0.7.2.  It is triggered by MyData attempting to update progress bars.  A failure to update a progress bar shouldn't raise a critical error.
```
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/python/2.7.14/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ec2-user/mydata/mydata/utils/progress.py", line 41, in MonitorProgress
    uploadModel.dataFileId)
  File "/home/ec2-user/mydata/mydata/models/datafile.py", line 100, in GetDataFileFromId
    response.raise_for_status()
  File "/home/ec2-user/virtualenvs/mydata/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: https://store.erc.monash.edu.au/api/v1/mydata_dataset_file/8747542/?format=json
```

**Comment by wettenhj** [comment]
![mydata_404_error](https://user-images.githubusercontent.com/2209245/45194451-73a79080-b296-11e8-9832-39d33e897d24.png)
