### ISSUE TITLE
Unicode characters in dataset folder names lead to unexpected behaviour

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mydata#28]
MyData was scanning dataset folders and came across some folders whose names ended with the Unicode character u'\uf028'.

As a result, urllib.quote(description) in mydata/models/dataset.py failed:

```
2015-11-05 14:38:28,947 - mydata.controllers.folders - 410 - StartDataUploads - StartDataUploadsThread - ERROR - Traceback (most recent call last):
  File "C:\Users\wettenhj\Desktop\git\mydata\master\build\MyData\out00-PYZ.pyz\mydata.controllers.folders", line 408, in StartDataUploads
  File "C:\Users\wettenhj\Desktop\git\mydata\master\build\MyData\out00-PYZ.pyz\mydata.models.dataset", line 130, in CreateDatasetIfNecessary
  File "C:\Users\wettenhj\Desktop\git\mydata\master\build\MyData\out00-PYZ.pyz\urllib", line 1282, in quote
KeyError: u'\uf028'
```

Then, MyData.exe somehow ended up using 100% of CPU.

In this case, it appears that the u'\uf028' Unicode character was added to the end of the folder names unintentionally, so it can just be removed before re-running MyData.

MyData doesn't necessarily need to support folder names including Unicode characters, but if we choose not to support Unicode folder names, then MyData should at least be able to handle this exception more gracefully.

**Comment by wettenhj** [comment]
Some attempts were made to support Unicode characters in MyData, but then in turned out that MyTardis doesn't support Unicode Dataset names or DataFile names yet, so there's no point in trying to support them in MyData.  Instead, some effort has been made to ensure that exceptions are reported more gracefully when Unicode characters are found in file or folder names.

See:

https://github.com/mytardis/mydata/commit/21d15c933f94e39e747a85b8bc701c049c51f875
https://github.com/mytardis/mydata/commit/fc5a5f98a31ba309642cb225c90daaf3fe7701cb
https://github.com/mytardis/mydata/commit/6cc1a88dd5607aa211a014695a5e9bfd0ead1e2d
https://github.com/mytardis/mydata/commit/5fb856272765638608fe2bb3fb27acc76aeb2f4e
https://github.com/mytardis/mydata/commit/dc68871ee19f193c96831cc4bc5627c0c9ffd7d2

These changes will be included in v0.7.0-beta5 and later.
