### ISSUE TITLE
errors in MyData log (running on Mac) 

### ISSUE THREAD

**Issue by sharynys** [mytardis/mydata#44]
This occurs when I save new settings in MyData. Please let me know if you need screenshots of settings. Here is the log...

2016-06-08 11:40:16,700 - __init__.pyc - 454 - SettingsDialogValidation - MainThread - DEBUG - Starting thread SettingsModelValidationThread
2016-06-08 11:40:16,774 - __init__.pyc - 456 - SettingsDialogValidation - MainThread - DEBUG - Started thread SettingsModelValidationThread
2016-06-08 11:40:16,834 - __init__.pyc - 361 - Validate - SettingsModelValidationThread - DEBUG - Starting run() method for thread SettingsModelValidationThread
2016-06-08 11:40:16,963 - uploader.pyc - 650 - GetActiveNetworkInterfaces - CheckConnectivityThread - INFO - Determining the active network interface...
2016-06-08 11:40:17,041 - __init__.pyc - 182 - CheckConnectivityWorker - CheckConnectivityThread - DEBUG - Found at least one active network interface: en0.
2016-06-08 11:40:17,051 - __init__.pyc - 454 - SettingsDialogValidation - MainThread - DEBUG - Starting thread SettingsModelValidationThread
2016-06-08 11:40:17,072 - __init__.pyc - 456 - SettingsDialogValidation - MainThread - DEBUG - Started thread SettingsModelValidationThread
2016-06-08 11:40:17,153 - __init__.pyc - 361 - Validate - SettingsModelValidationThread - DEBUG - Starting run() method for thread SettingsModelValidationThread
2016-06-08 11:40:17,154 - settings.pyc - 853 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - checking folder structure...
2016-06-08 11:40:17,159 - settings.pyc - 1542 - PerformFolderStructureValidation - SettingsModelValidationThread - DEBUG - SettingsModel folder structure validation succeeded!
2016-06-08 11:40:17,159 - settings.pyc - 864 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - checking MyTardis URL...
2016-06-08 11:40:17,345 - settings.pyc - 949 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - checking MyTardis credentials...
2016-06-08 11:40:17,399 - settings.pyc - 977 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - checking MyTardis facility...
2016-06-08 11:40:17,466 - settings.pyc - 1025 - Validate - SettingsModelValidationThread - WARNING - For now, we are assuming that if we find an instrument record with the correct name and facility, then it must be the correct instrument record to use with this MyData instance. However, if the instrument record we find is associated with a different uploader instance (suggesting a different MyData instance), then we really shouldn't reuse the same instrument record.
2016-06-08 11:40:17,511 - instrument.pyc - 154 - GetInstrument - SettingsModelValidationThread - DEBUG - Found instrument record for name "Nikon A1 Microscope" in facility "Microbial Imaging Facility"
2016-06-08 11:40:17,513 - settings.pyc - 1052 - Validate - SettingsModelValidationThread - DEBUG - Validating email address.
2016-06-08 11:40:17,609 - settings.pyc - 1058 - Validate - SettingsModelValidationThread - DEBUG - Done validating email address.
2016-06-08 11:40:17,611 - settings.pyc - 1073 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - checking if MyData is set to start automatically...
2016-06-08 11:40:17,617 - settings.pyc - 1076 - Validate - SettingsModelValidationThread - WARNING - This auto-start on login stuff shouldn't really be in settings validation.  I just put it here temporarily to ensure it doesn't run in the main thread.
2016-06-08 11:40:19,703 - settings.pyc - 1228 - Validate - SettingsModelValidationThread - INFO - MyData is already set to start automatically on login.
2016-06-08 11:40:19,733 - settings.pyc - 1279 - Validate - SettingsModelValidationThread - DEBUG - Settings validation - succeeded!
2016-06-08 11:40:19,765 - __init__.pyc - 447 - Validate - SettingsModelValidationThread - DEBUG - Finished running settingsModel.Validate() 4
2016-06-08 11:40:19,765 - __init__.pyc - 449 - Validate - SettingsModelValidationThread - DEBUG - Finishing run() method for thread SettingsModelValidationThread
2016-06-08 11:40:24,975 - __init__.pyc - 571 - ProvideSettingsValidationResults - MainThread - DEBUG - Settings were valid, so we'll save the settings to disk and close the Settings dialog.
2016-06-08 11:40:24,985 - uploader.pyc - 650 - GetActiveNetworkInterfaces - MainThread - INFO - Determining the active network interface...
2016-06-08 11:40:25,061 - uploader.pyc - 259 - __init__ - MainThread - INFO - The active network interface is: en0
2016-06-08 11:40:25,112 - settings.pyc - 726 - SaveToDisk - MainThread - INFO - Saved settings to /Users/108752/Library/Application Support/MyData/MyData.cfg
2016-06-08 11:40:25,881 - __init__.pyc - 594 - ProvideSettingsValidationResults - MainThread - DEBUG - Traceback (most recent call last):
  File "mydata/events/__init__.pyc", line 589, in ProvideSettingsValidationResults
  File "wx/_windows.pyc", line 809, in EndModal
PyAssertionError: C++ assertion "Assert failure" failed at /BUILD/wxPython-src-2.9.5.0/src/osx/cocoa/dataview.mm(2806) in MacRender(): Text renderer cannot render value because of wrong value type; value type: PyObject

2016-06-08 11:40:26,145 - MyData.pyc - 1063 - OnSettings - MainThread - DEBUG - settingsDialog.ShowModal() returned wx.ID_OK
2016-06-08 11:40:26,152 - schedule.pyc - 31 - ApplySchedule - MainThread - DEBUG - Getting schedule type from settings dialog.
2016-06-08 11:40:26,159 - schedule.pyc - 42 - ApplySchedule - MainThread - DEBUG - Schedule type is Manually.
2016-06-08 11:40:26,166 - schedule.pyc - 45 - ApplySchedule - MainThread - DEBUG - Finished processing schedule type.

**Comment by wettenhj** [comment]
What version is this?

**Comment by sharynys** [comment]
Yosemite 10.10.2 and MyData_v0.5.4.dmg

**Comment by sharynys** [comment]
sorry ... if I do an About on MyData it says v0.5.3. I downloaded the 'current' version from the "read the docs" page.

**Comment by wettenhj** [comment]
OK, thanks for letting us know.  This sounds like a known issue in v0.5.3.  Can you please try again to verify that you have downloaded and installed MyData_v0.5.4.dmg?  v0.5.4 is the "current" version now, but it's possible that you downloaded the DMG from a cached version of the "read the docs" page.  If you do have the correct version number (0.5.4) in the DMG filename, i.e. "MyData_v0.5.4.dmg", maybe try running MyData directly form the DMG, and checking "About MyData" for the version number.  Then if that fixes the version number in the About dialog (it should be 0.5.4), try recopying the MyData.app from the DMG to your Applications folder.

**Comment by sharynys** [comment]
Hi, I re-downloaded and reinstalled and the error has gone. The About also reads the correct version. Must have been a caching issue as the file I downloaded originally was definitely named MyData_v0.5.4.dmg.
